<?php

namespace Database\Seeders;

use App\Models\Promotion;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class PromotionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $promotions = [
            // Active percentage discounts
            [
                'code' => 'WELCOME10',
                'name' => 'Chào mừng khách hàng mới',
                'description' => 'Giảm 10% cho đơn hàng đầu tiên',
                'type' => 'percentage',
                'value' => 10,
                'min_order_value' => 500000,
                'max_discount' => 200000,
                'usage_limit' => 1000,
                'usage_per_user' => 1,
                'usage_count' => 0,
                'starts_at' => $now->copy()->subDays(30),
                'expires_at' => $now->copy()->addMonths(3),
                'is_active' => true,
            ],
            [
                'code' => 'UITECH15',
                'name' => 'Ưu đãi UITech',
                'description' => 'Giảm 15% cho tất cả sản phẩm',
                'type' => 'percentage',
                'value' => 15,
                'min_order_value' => 1000000,
                'max_discount' => 500000,
                'usage_limit' => 500,
                'usage_per_user' => 2,
                'usage_count' => 45,
                'starts_at' => $now->copy()->subDays(7),
                'expires_at' => $now->copy()->addMonths(1),
                'is_active' => true,
            ],
            [
                'code' => 'VIP20',
                'name' => 'Ưu đãi VIP',
                'description' => 'Giảm 20% cho khách hàng VIP',
                'type' => 'percentage',
                'value' => 20,
                'min_order_value' => 2000000,
                'max_discount' => 1000000,
                'usage_limit' => 200,
                'usage_per_user' => 5,
                'usage_count' => 12,
                'starts_at' => $now->copy()->subDays(14),
                'expires_at' => $now->copy()->addMonths(2),
                'is_active' => true,
            ],
            [
                'code' => 'SUMMER25',
                'name' => 'Khuyến mãi mùa hè',
                'description' => 'Giảm 25% - Chào hè 2024',
                'type' => 'percentage',
                'value' => 25,
                'min_order_value' => 3000000,
                'max_discount' => 1500000,
                'usage_limit' => 100,
                'usage_per_user' => 1,
                'usage_count' => 0,
                'starts_at' => $now->copy(),
                'expires_at' => $now->copy()->addMonths(2),
                'is_active' => true,
            ],

            // Fixed amount discounts
            [
                'code' => 'GIAM50K',
                'name' => 'Giảm 50K',
                'description' => 'Giảm ngay 50.000₫ cho đơn hàng từ 300K',
                'type' => 'fixed',
                'value' => 50000,
                'min_order_value' => 300000,
                'max_discount' => null,
                'usage_limit' => 2000,
                'usage_per_user' => 3,
                'usage_count' => 156,
                'starts_at' => $now->copy()->subDays(10),
                'expires_at' => $now->copy()->addDays(20),
                'is_active' => true,
            ],
            [
                'code' => 'GIAM100K',
                'name' => 'Giảm 100K',
                'description' => 'Giảm ngay 100.000₫ cho đơn hàng từ 1 triệu',
                'type' => 'fixed',
                'value' => 100000,
                'min_order_value' => 1000000,
                'max_discount' => null,
                'usage_limit' => 500,
                'usage_per_user' => 2,
                'usage_count' => 78,
                'starts_at' => $now->copy()->subDays(5),
                'expires_at' => $now->copy()->addDays(25),
                'is_active' => true,
            ],
            [
                'code' => 'GIAM200K',
                'name' => 'Giảm 200K',
                'description' => 'Giảm ngay 200.000₫ cho đơn hàng từ 2 triệu',
                'type' => 'fixed',
                'value' => 200000,
                'min_order_value' => 2000000,
                'max_discount' => null,
                'usage_limit' => 300,
                'usage_per_user' => 2,
                'usage_count' => 34,
                'starts_at' => $now->copy()->subDays(3),
                'expires_at' => $now->copy()->addDays(30),
                'is_active' => true,
            ],
            [
                'code' => 'GIAM500K',
                'name' => 'Mega Sale 500K',
                'description' => 'Giảm ngay 500.000₫ cho đơn hàng từ 5 triệu',
                'type' => 'fixed',
                'value' => 500000,
                'min_order_value' => 5000000,
                'max_discount' => null,
                'usage_limit' => 100,
                'usage_per_user' => 1,
                'usage_count' => 8,
                'starts_at' => $now->copy(),
                'expires_at' => $now->copy()->addDays(14),
                'is_active' => true,
            ],

            // Category/Event specific
            [
                'code' => 'PCGAMING',
                'name' => 'PC Gaming Sale',
                'description' => 'Giảm 10% cho PC Gaming',
                'type' => 'percentage',
                'value' => 10,
                'min_order_value' => 5000000,
                'max_discount' => 1000000,
                'usage_limit' => 200,
                'usage_per_user' => 1,
                'usage_count' => 23,
                'starts_at' => $now->copy()->subDays(7),
                'expires_at' => $now->copy()->addMonths(1),
                'is_active' => true,
            ],
            [
                'code' => 'FREESHIP',
                'name' => 'Miễn phí vận chuyển',
                'description' => 'Giảm 50K phí ship cho đơn từ 500K',
                'type' => 'fixed',
                'value' => 50000,
                'min_order_value' => 500000,
                'max_discount' => null,
                'usage_limit' => 1000,
                'usage_per_user' => 5,
                'usage_count' => 234,
                'starts_at' => $now->copy()->subDays(30),
                'expires_at' => $now->copy()->addMonths(2),
                'is_active' => true,
            ],
            [
                'code' => 'BIRTHDAY',
                'name' => 'Sinh nhật UITech',
                'description' => 'Giảm 30% nhân dịp sinh nhật UITech',
                'type' => 'percentage',
                'value' => 30,
                'min_order_value' => 1000000,
                'max_discount' => 2000000,
                'usage_limit' => 1000,
                'usage_per_user' => 1,
                'usage_count' => 0,
                'starts_at' => $now->copy(),
                'expires_at' => $now->copy()->addDays(7),
                'is_active' => true,
            ],
            [
                'code' => 'NEWYEAR24',
                'name' => 'Năm mới 2024',
                'description' => 'Ưu đãi năm mới - Giảm 15%',
                'type' => 'percentage',
                'value' => 15,
                'min_order_value' => 500000,
                'max_discount' => 300000,
                'usage_limit' => 500,
                'usage_per_user' => 1,
                'usage_count' => 0,
                'starts_at' => $now->copy(),
                'expires_at' => $now->copy()->addMonths(1),
                'is_active' => true,
            ],

            // Flash sales (limited quantity)
            [
                'code' => 'FLASH10',
                'name' => 'Flash Sale 10%',
                'description' => 'Flash sale - Giảm 10% (chỉ 50 mã)',
                'type' => 'percentage',
                'value' => 10,
                'min_order_value' => 200000,
                'max_discount' => 100000,
                'usage_limit' => 50,
                'usage_per_user' => 1,
                'usage_count' => 12,
                'starts_at' => $now->copy(),
                'expires_at' => $now->copy()->addDays(3),
                'is_active' => true,
            ],
            [
                'code' => 'FLASH30K',
                'name' => 'Flash Sale 30K',
                'description' => 'Flash sale - Giảm ngay 30K',
                'type' => 'fixed',
                'value' => 30000,
                'min_order_value' => 100000,
                'max_discount' => null,
                'usage_limit' => 100,
                'usage_per_user' => 1,
                'usage_count' => 67,
                'starts_at' => $now->copy(),
                'expires_at' => $now->copy()->addDays(2),
                'is_active' => true,
            ],

            // Student discount
            [
                'code' => 'STUDENT5',
                'name' => 'Ưu đãi sinh viên',
                'description' => 'Giảm 5% cho sinh viên',
                'type' => 'percentage',
                'value' => 5,
                'min_order_value' => 100000,
                'max_discount' => 100000,
                'usage_limit' => null,
                'usage_per_user' => 10,
                'usage_count' => 456,
                'starts_at' => $now->copy()->subMonths(6),
                'expires_at' => $now->copy()->addYear(),
                'is_active' => true,
            ],

            // Expired coupons (for testing invalid states)
            [
                'code' => 'EXPIRED20',
                'name' => 'Đã hết hạn',
                'description' => 'Mã này đã hết hạn',
                'type' => 'percentage',
                'value' => 20,
                'min_order_value' => 500000,
                'max_discount' => 200000,
                'usage_limit' => 100,
                'usage_per_user' => 1,
                'usage_count' => 45,
                'starts_at' => $now->copy()->subMonths(2),
                'expires_at' => $now->copy()->subDays(5),
                'is_active' => true,
            ],

            // Exhausted coupons
            [
                'code' => 'SOLDOUT',
                'name' => 'Đã hết lượt',
                'description' => 'Mã này đã hết lượt sử dụng',
                'type' => 'fixed',
                'value' => 100000,
                'min_order_value' => 500000,
                'max_discount' => null,
                'usage_limit' => 100,
                'usage_per_user' => 1,
                'usage_count' => 100,
                'starts_at' => $now->copy()->subDays(30),
                'expires_at' => $now->copy()->addDays(30),
                'is_active' => true,
            ],

            // Inactive coupons
            [
                'code' => 'INACTIVE50',
                'name' => 'Chưa kích hoạt',
                'description' => 'Mã này chưa được kích hoạt',
                'type' => 'percentage',
                'value' => 50,
                'min_order_value' => 1000000,
                'max_discount' => 500000,
                'usage_limit' => 100,
                'usage_per_user' => 1,
                'usage_count' => 0,
                'starts_at' => $now->copy(),
                'expires_at' => $now->copy()->addMonths(1),
                'is_active' => false,
            ],

            // Future coupon
            [
                'code' => 'FUTURE2025',
                'name' => 'Năm mới 2025',
                'description' => 'Mã này chưa có hiệu lực',
                'type' => 'percentage',
                'value' => 25,
                'min_order_value' => 1000000,
                'max_discount' => 500000,
                'usage_limit' => 500,
                'usage_per_user' => 1,
                'usage_count' => 0,
                'starts_at' => Carbon::create(2025, 1, 1),
                'expires_at' => Carbon::create(2025, 2, 1),
                'is_active' => true,
            ],
        ];

        foreach ($promotions as $promotion) {
            Promotion::updateOrCreate(
                ['code' => $promotion['code']],
                $promotion
            );
        }
    }
}
